use super::CompileErrorKind;

impl CompileErrorKind {
    pub fn annotation(&self) -> &'static str {
        match self {
            Self::UndefinedVariable(_) => "not found in this scope",
            Self::VariableAlreadyDefined(_) => "already defined here",
            Self::UndefinedFunction(_) => "not found in this scope",
            Self::AssignToImmutable(_) => "variable is not mutable",
            Self::AssignToLoopVariable(_) => "controlled by the for loop",
            Self::InvalidAssignmentTarget => "cannot assign to this",
            Self::RecursionDepthExceeded { .. } => "nesting limit exceeded",
            Self::CommentNestingTooDeep { .. } => "nesting limit exceeded",
            Self::UnexpectedToken { .. } => "unexpected token",
            Self::ReturnOutsideFunction => "not inside a function",
            Self::BreakOutsideLoop => "not inside a loop",
            Self::ContinueOutsideLoop => "not inside a loop",
            Self::TypeMismatch { .. } => "type mismatch",
            Self::ArityMismatch { .. } => "wrong number of arguments",
            Self::NotCallable { .. } => "not callable",
            Self::MemberAccess { .. } => "invalid member access",
            Self::InfiniteType { .. } => "infinite type",
            Self::UnknownType { .. } => "unknown type",
            Self::InvalidCast { .. } => "invalid cast",
            Self::RecursionLimitExceeded => "recursion limit",
            Self::ModuleNotFound { .. } => "module not found",
            Self::CircularDependency { .. } => "creates circular dependency",
            Self::SymbolNotPublic { .. } => "symbol is not public",
            Self::ReservedModuleSegment { .. } => "reserved module path segment",
            Self::SymbolNotFound { .. } => "no such item in that module",
            Self::SymbolConflict { .. } => "this import name is already taken",
            Self::ForeignHeaderImport { .. } => "C header import is not implemented yet",
            Self::NeedsOutsidePrologue => "`needs` out of the module prologue",
            Self::WildcardImport { .. } => "wildcard import is not implemented yet",
            Self::ConflictingExternalSymbol { .. } => "this symbol is claimed here",
            Self::ConflictingForeignDeclarations { .. } => "this declaration disagrees",
            Self::ReservedRuntimeSymbol { .. } => "this name belongs to the runtime",
            Self::MalformedForeignDecl { .. } => "not a well formed external declaration",
            Self::ForeignSignatureType { .. } => "outside the external type surface",
            Self::TypeInferenceError(_) => "type inference failed",
            Self::LinkedLibraryClaimsRuntimeSymbol { .. } => "this program is linked against it",
            Self::BackendDiagnostic { .. } => "backend error",
            _ => "",
        }
    }
}
